### PR TITLE
Allow zero length column

### PR DESCRIPTION
**Pull request by OndroNR**
Hi, we have DBF file with column that have zero column length and no data in it. I have altered DBF::Column#initialize to accept zero length columns. All tests passes.

### CODE REVIEW

**Comment by infused** [comment]
What is the column type of the 0 length column? Also, what is the version of the dbf file (table.version)?

**Comment by OndroNR** [comment]
Numeric. There are other Character zero length columns after this one, that would possibly fail. Version is "03" (table.version), dBASE III (DBFView)

**Comment by infused** [comment]
What is the expected output of a zero length column?  I'm thinking that the value for any zero length column should be nil regardless of the column type.  Do you agree?

**Comment by OndroNR** [comment]
Nil should be fine as the value is missing.

**Comment by infused** [comment]
Thanks for contributing this work!  I've released version 2.0.10 that includes these changes.

**Comment by OndroNR** [comment]
Thanks to you as well :)

**Pull request merged**
